import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const publishableKey = 'pk_test_ZXBpYy1zb2xlLTMzLmNsZXJrLmFjY291bnRzLmRldiQ';
  return (
    <html lang="en">
      <ClerkProvider
        publishableKey={publishableKey}
      >
        <body className={poppins.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
